vich_uploader:
    db_driver: orm
    
    mappings:
        dish_image:
            uri_prefix: /images/dishes
            upload_destination: '%kernel.project_dir%/public/images/dishes'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            
        order_file:  
            uri_prefix: /uploads/orders
            upload_destination: '%kernel.project_dir%/public/uploads/orders'
            namer: Vich\UploaderBundle\Naming\OrignameNamer